data:
  raw_path: "data/raw/forest_cover_data.xlsx"
  processed_path: "data/processed/forest_cover_processed.csv"

model:
  test_size: 0.2
  random_state: 42
  n_estimators: 200
  max_depth: 20

paths:
  models: "models/"
  reports: "reports/"
  figures: "reports/figures/"
